//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdPal.Ext.Spotify.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdPal.Ext.Spotify.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        public static string ContextMenuResultAddToQueueTitle {
            get {
                return ResourceManager.GetString("ContextMenuResultAddToQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to album.
        /// </summary>
        public static string ContextMenuResultGoToAlbumTitle {
            get {
                return ResourceManager.GetString("ContextMenuResultGoToAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not refresh available devices.
        /// </summary>
        public static string DeviceCacheErrorToast {
            get {
                return ResourceManager.GetString("DeviceCacheErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed available devices.
        /// </summary>
        public static string DeviceCacheSavedToast {
            get {
                return ResourceManager.GetString("DeviceCacheSavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        public static string EmptyErrorTitle {
            get {
                return ResourceManager.GetString("EmptyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found..
        /// </summary>
        public static string EmptyResultsTitle {
            get {
                return ResourceManager.GetString("EmptyResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not Add to queue.
        /// </summary>
        public static string ErrorAddToQueueToast {
            get {
                return ResourceManager.GetString("ErrorAddToQueueToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write session log.
        /// </summary>
        public static string ErrorJournalAppend {
            get {
                return ResourceManager.GetString("ErrorJournalAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load top tracks.
        /// </summary>
        public static string ErrorLoadingTopTracksTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingTopTracksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load tracks.
        /// </summary>
        public static string ErrorLoadingTracksTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingTracksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log in..
        /// </summary>
        public static string ErrorLoginToast {
            get {
                return ResourceManager.GetString("ErrorLoginToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search through and control Spotify..
        /// </summary>
        public static string ExtensionDescription {
            get {
                return ResourceManager.GetString("ExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify control.
        /// </summary>
        public static string ExtensionDisplayName {
            get {
                return ResourceManager.GetString("ExtensionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string ExtensionSettingClientId {
            get {
                return ResourceManager.GetString("ExtensionSettingClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Spotify&apos;s app client id..
        /// </summary>
        public static string ExtensionSettingClientIdDescription {
            get {
                return ResourceManager.GetString("ExtensionSettingClientIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Wildcard.
        /// </summary>
        public static string ExtensionSettingFilterWildcard {
            get {
                return ResourceManager.GetString("ExtensionSettingFilterWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter wildcard character used to prepend a filter, e.g. /album or !album.
        /// </summary>
        public static string ExtensionSettingFilterWildcardDescription {
            get {
                return ResourceManager.GetString("ExtensionSettingFilterWildcardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search through and control Spotify
        ///as {0} ({1}).
        /// </summary>
        public static string ExtensionStatusDescription {
            get {
                return ResourceManager.GetString("ExtensionStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎧 Logged in as {0} ({1}).
        /// </summary>
        public static string LoginSuccessToast {
            get {
                return ResourceManager.GetString("LoginSuccessToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Logged in, but failed to get user info.
        /// </summary>
        public static string LoginUserInfoEmptyToast {
            get {
                return ResourceManager.GetString("LoginUserInfoEmptyToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device selection failed with both cache and API query.
        /// </summary>
        public static string PlayerCommandDeviceRetrievalFailedEx {
            get {
                return ResourceManager.GetString("PlayerCommandDeviceRetrievalFailedEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select valid device from Spotify API.
        /// </summary>
        public static string PlayerCommandDeviceSelectionFailedEx {
            get {
                return ResourceManager.GetString("PlayerCommandDeviceSelectionFailedEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing expired session….
        /// </summary>
        public static string PlayerCommandSessionHealingToast {
            get {
                return ResourceManager.GetString("PlayerCommandSessionHealingToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string ResultAlbumSubTitle {
            get {
                return ResourceManager.GetString("ResultAlbumSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ResultArtistSubTitle {
            get {
                return ResourceManager.GetString("ResultArtistSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to authorize the extension to use the Spotify API..
        /// </summary>
        public static string ResultLoginSubTitle {
            get {
                return ResourceManager.GetString("ResultLoginSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ResultLoginTitle {
            get {
                return ResourceManager.GetString("ResultLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your client ID in the extension&apos;s settings..
        /// </summary>
        public static string ResultMissingClientIdSubTitle {
            get {
                return ResourceManager.GetString("ResultMissingClientIdSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify - Missing client ID.
        /// </summary>
        public static string ResultMissingClientIdTitle {
            get {
                return ResourceManager.GetString("ResultMissingClientIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string ResultNextTrackTitle {
            get {
                return ResourceManager.GetString("ResultNextTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback.
        /// </summary>
        public static string ResultPausePlaybackTitle {
            get {
                return ResourceManager.GetString("ResultPausePlaybackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string ResultPlaylistSubTitle {
            get {
                return ResourceManager.GetString("ResultPlaylistSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ResultPlayName {
            get {
                return ResourceManager.GetString("ResultPlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        public static string ResultPreviousTrackTitle {
            get {
                return ResourceManager.GetString("ResultPreviousTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume playback.
        /// </summary>
        public static string ResultResumePlaybackTitle {
            get {
                return ResourceManager.GetString("ResultResumePlaybackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set repeat to context.
        /// </summary>
        public static string ResultSetRepeatContextTitle {
            get {
                return ResourceManager.GetString("ResultSetRepeatContextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set repeat to off.
        /// </summary>
        public static string ResultSetRepeatOffTitle {
            get {
                return ResourceManager.GetString("ResultSetRepeatOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set repeat to track.
        /// </summary>
        public static string ResultSetRepeatTrackTitle {
            get {
                return ResourceManager.GetString("ResultSetRepeatTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string ResultSongBySubTitle {
            get {
                return ResourceManager.GetString("ResultSongBySubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        public static string ResultSongExplicitSubTitle {
            get {
                return ResourceManager.GetString("ResultSongExplicitSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string ResultSongSubTitle {
            get {
                return ResourceManager.GetString("ResultSongSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle playback.
        /// </summary>
        public static string ResultTogglePlaybackTitle {
            get {
                return ResourceManager.GetString("ResultTogglePlaybackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off shuffle.
        /// </summary>
        public static string ResultTurnOffShuffleTitle {
            get {
                return ResourceManager.GetString("ResultTurnOffShuffleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on shuffle.
        /// </summary>
        public static string ResultTurnOnShuffleTitle {
            get {
                return ResourceManager.GetString("ResultTurnOnShuffleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        public static string SearchTypeAlbum {
            get {
                return ResourceManager.GetString("SearchTypeAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        public static string SearchTypeArtist {
            get {
                return ResourceManager.GetString("SearchTypeArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audiobook.
        /// </summary>
        public static string SearchTypeAudiobook {
            get {
                return ResourceManager.GetString("SearchTypeAudiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episode.
        /// </summary>
        public static string SearchTypeEpisode {
            get {
                return ResourceManager.GetString("SearchTypeEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist.
        /// </summary>
        public static string SearchTypePlaylist {
            get {
                return ResourceManager.GetString("SearchTypePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string SearchTypeShow {
            get {
                return ResourceManager.GetString("SearchTypeShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        public static string SearchTypeTrack {
            get {
                return ResourceManager.GetString("SearchTypeTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Top Tracks.
        /// </summary>
        public static string TopTracksTitle {
            get {
                return ResourceManager.GetString("TopTracksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to {0}.
        /// </summary>
        public static string TransferPlaybackCommandName {
            get {
                return ResourceManager.GetString("TransferPlaybackCommandName", resourceCulture);
            }
        }
    }
}
