//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdPal.Ext.Spotify.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdPal.Ext.Spotify.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        internal static string ContextMenuResultAddToQueueTitle {
            get {
                return ResourceManager.GetString("ContextMenuResultAddToQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string EmptyErrorTitle {
            get {
                return ResourceManager.GetString("EmptyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found..
        /// </summary>
        internal static string EmptyResultsTitle {
            get {
                return ResourceManager.GetString("EmptyResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search through and control Spotify..
        /// </summary>
        internal static string ExtensionDescription {
            get {
                return ResourceManager.GetString("ExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify control.
        /// </summary>
        internal static string ExtensionDisplayName {
            get {
                return ResourceManager.GetString("ExtensionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Spotify&apos;s app client id..
        /// </summary>
        internal static string ExtensionSettingClientIdDescription {
            get {
                return ResourceManager.GetString("ExtensionSettingClientIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string ResultAlbumSubTitle {
            get {
                return ResourceManager.GetString("ResultAlbumSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string ResultAlbumTypeAlbum {
            get {
                return ResourceManager.GetString("ResultAlbumTypeAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation.
        /// </summary>
        internal static string ResultAlbumTypeCompilation {
            get {
                return ResourceManager.GetString("ResultAlbumTypeCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string ResultAlbumTypeSingle {
            get {
                return ResourceManager.GetString("ResultAlbumTypeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string ResultArtistSubTitle {
            get {
                return ResourceManager.GetString("ResultArtistSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        internal static string ResultEpisodeSubTitle {
            get {
                return ResourceManager.GetString("ResultEpisodeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to authorize the extension to use the Spotify API..
        /// </summary>
        internal static string ResultLoginSubTitle {
            get {
                return ResourceManager.GetString("ResultLoginSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ResultLoginTitle {
            get {
                return ResourceManager.GetString("ResultLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your client ID in the extension&apos;s settings..
        /// </summary>
        internal static string ResultMissingClientIdSubTitle {
            get {
                return ResourceManager.GetString("ResultMissingClientIdSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify - Missing client ID.
        /// </summary>
        internal static string ResultMissingClientIdTitle {
            get {
                return ResourceManager.GetString("ResultMissingClientIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        internal static string ResultNextTrackTitle {
            get {
                return ResourceManager.GetString("ResultNextTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback.
        /// </summary>
        internal static string ResultPausePlaybackTitle {
            get {
                return ResourceManager.GetString("ResultPausePlaybackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string ResultPlaylistSubTitle {
            get {
                return ResourceManager.GetString("ResultPlaylistSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string ResultPlayName {
            get {
                return ResourceManager.GetString("ResultPlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        internal static string ResultPreviousTrackTitle {
            get {
                return ResourceManager.GetString("ResultPreviousTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume playback.
        /// </summary>
        internal static string ResultResumePlaybackTitle {
            get {
                return ResourceManager.GetString("ResultResumePlaybackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set repeat to context.
        /// </summary>
        internal static string ResultSetRepeatContextTitle {
            get {
                return ResourceManager.GetString("ResultSetRepeatContextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set repeat to off.
        /// </summary>
        internal static string ResultSetRepeatOffTitle {
            get {
                return ResourceManager.GetString("ResultSetRepeatOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set repeat to track.
        /// </summary>
        internal static string ResultSetRepeatTrackTitle {
            get {
                return ResourceManager.GetString("ResultSetRepeatTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string ResultSongBySubTitle {
            get {
                return ResourceManager.GetString("ResultSongBySubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        internal static string ResultSongExplicitSubTitle {
            get {
                return ResourceManager.GetString("ResultSongExplicitSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        internal static string ResultSongSubTitle {
            get {
                return ResourceManager.GetString("ResultSongSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle playback.
        /// </summary>
        internal static string ResultTogglePlaybackTitle {
            get {
                return ResourceManager.GetString("ResultTogglePlaybackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off shuffle.
        /// </summary>
        internal static string ResultTurnOffShuffleTitle {
            get {
                return ResourceManager.GetString("ResultTurnOffShuffleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on shuffle.
        /// </summary>
        internal static string ResultTurnOnShuffleTitle {
            get {
                return ResourceManager.GetString("ResultTurnOnShuffleTitle", resourceCulture);
            }
        }
    }
}
